package asns

const (
	ActivityTypeAccept          = "Accept"
	ActivityTypeAdd             = "Add"
	ActivityTypeAnnounce        = "Announce"
	ActivityTypeArrive          = "Arrive"
	ActivityTypeBlock           = "Block"
	ActivityTypeCreate          = "Create"
	ActivityTypeDelete          = "Delete"
	ActivityTypeDislike         = "Dislike"
	ActivityTypeFlag            = "Flag"
	ActivityTypeFollow          = "Follow"
	ActivityTypeIgnore          = "Ignore"
	ActivityTypeInvite          = "Invite"
	ActivityTypeJoin            = "Join"
	ActivityTypeLeave           = "Leave"
	ActivityTypeLike            = "Like"
	ActivityTypeListen          = "Listen"
	ActivityTypeMove            = "Move"
	ActivityTypeOffer           = "Offer"
	ActivityTypeQuestion        = "Question"
	ActivityTypeReject          = "Reject"
	ActivityTypeRead            = "Read"
	ActivityTypeRemove          = "Remove"
	ActivityTypeTentativeReject = "TentativeReject"
	ActivityTypeTentativeAccept = "TentativeAccept"
	ActivityTypeTravel          = "Travel"
	ActivityTypeUndo            = "Undo"
	ActivityTypeUpdate          = "Update"
	ActivityTypeView            = "View"
)
